### ISSUE TITLE
How is it possible to have so many manifest fragments? 

### ISSUE THREAD

**Issue by bnlawrence** [bnlawrence/cfs#32]
While working on #16, we are getting this error: 
```
RuntimeError: Number of of manifest fragments (1560) not equal to time data length (780).
```
which my first guess arises because the second time we add a cfa file with the same temporal domain as the first one (i.e another ensemble member) we are reusing the same manifest for both ensemble members. Just a guess at this stage ... 

So now we need a new unit test :-)

**Comment by bnlawrence** [comment]
Ok, it looks like something _is_ going wrong with the CFA ingest with two ensemble members. The first call to subset shows manifests like this from the off ... need to investigate how that happens.

**Comment by bnlawrence** [comment]
Well, maybe the problem is at source. In the CFA file, we can find that there are aggregated variables with mixed files. E.g. for the following
```
flist = cf.read('CANARI_1_cs125_atmos.cfa')
ff = f.select_by_identity('eastward_wind')
```
we find that for ff =
```
<CF Field: eastward_wind(time(93600), atmosphere_hybrid_height_coordinate(85), latitude(324), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(780), atmosphere_hybrid_height_coordinate(85), latitude(324), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(23400), latitude(324), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(780), latitude(324), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(780), latitude(325), longitude(432)) m s-1>,
 <CF Field: eastward_wind(height(2), time(561600), latitude(325), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(780), air_pressure(36), latitude(325), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(780), air_pressure(36), latitude(325), longitude(1)) m s-1>,
 <CF Field: eastward_wind(time(23400), air_pressure(27), latitude(325), longitude(432)) m s-1>,
 <CF Field: eastward_wind(time(23400), air_pressure(39), latitude(325), longitude(1)) m s-1>,
 <CF Field: eastward_wind(time(93600), air_pressure(16), latitude(325), longitude(432)) m s-1>]
```
if we look at 
```
y= ff[-1]
y
<CF Field: eastward_wind(time(93600), air_pressure(16), latitude(325), longitude(432)) m s-1>
len(y.get_filenames())
1561
```
and look at some of them we see
```
unavailable:cs125_1_6hr_pt_cordex__195404-195404.nc',
 'unavailable:cs125_1_6hr_pt_cordex__199908-199908.nc',
 'unavailable:cs125_1_6hr_pt__200012-200012.nc',
 'unavailable:cs125_1_6hr_pt__195812-195812.nc',
 'unavailable:cs125_1_6hr_pt_cordex__199105-199105.nc',
 'unavailable:cs125_1_6hr_pt__195202-195202.nc',
```
which can't be right!

This might be fixed in the new CANARI aggregation files? Might be one for you to look at @davidhassell

**Comment by davidhassell** [comment]
That indeed is not right! I don't have the CFA file `cs125_1`, but in the original source (`cn134a_999`) there is no such mixing. Could you have a look inside `cs125_1*.cfa`? If that look OK (probably will) then it's likely an aggregation thing. We don't ned to aggregate the contents of the CFA fiel, so you could try: 

```python
flist = cf.read('CANARI_1_cs125_atmos.cfa', aggregate=False)
```


I'm firmly in the "new" cf-python camp, now. So we're going to remake the CFA files, anyway.

**Comment by bnlawrence** [comment]
It looks like using aggregate=False solves the problem. 

To some extent I think we should just go straight to new CFA. How hard would it be to get me a couple of "new" versions? I could then upgrade my CF and just go from there?  

(That said, there is obviously a problem with the aggregation as was, can we test it doesn't exist going forward?)

**Comment by bnlawrence** [comment]
(It seems that it has aggregated these two variables in some way: 
```
Variable: eastward_wind (Coupled Climate/HIST2/NCAS/atmos, r1i1p1f3) (14.3GiB)
Spatial Domain: {'name': 'N216', 'nominal_resolution': '50km', 'coordinates': 'air_pressure(7), latitude(325), longitude(432)'}
Time Domain: {'starting': <CF Data(): 1950-01-01 06:00:00 360_day>, 'ending': <CF Data(): 2015-01-01 00:00:00 360_day>, 'interval': '6 h (3900 samples).'}
Cell Methods: area : mean, time : point

Variable: eastward_wind (Coupled Climate/HIST2/NCAS/atmos, r1i1p1f3) (18.4GiB)
Spatial Domain: {'name': 'N216', 'nominal_resolution': '50km', 'coordinates': 'air_pressure(9), latitude(325), longitude(432)'}
Time Domain: {'starting': <CF Data(): 1950-01-01 06:00:00 360_day>, 'ending': <CF Data(): 2015-01-01 00:00:00 360_day>, 'interval': '6 h (3900 samples).'}
Cell Methods: area : mean, time : point
```

**Comment by bnlawrence** [comment]
Clearly both over air pressure ... but maybe we don't want it to do that if the two domains overlap as opposed to are contiguous (if that's the problem).

**Comment by bnlawrence** [comment]
Anyway, for my purposes, this is solved, so I'm closing the ticket.
